# Generated by Django 5.1.1 on 2024-09-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sensor_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_temp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('sensor_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_app.sensor_app')),
            ],
        ),
    ]
